// Product catalog built from the photos in E:\photos.
// `photo` is the photo's position when the folder is sorted by modified time (oldest first).
// `cut` holds per-photo background-removal settings (see cutout.cjs).

const SHADOW = { tolerance: 60, edgeLimit: 9 };
const WHITE = { tolerance: 6, edgeLimit: 5 };

module.exports = [
  // ---------- Cases ----------
  { photo: 0, cat: "cases", name: "NZXT H9 Flow White", brand: "NZXT", price: 52000, sale: 48000, stock: 7, featured: true, cut: WHITE,
    desc: "Dual-chamber mid-tower with panoramic glass and room for 10 fans.", specs: { "Form Factor": "Mid Tower", Glass: "Tempered, 3 sides", Colour: "White" } },
  { photo: 1, cat: "cases", name: "Lian Li O11 Dynamic EVO White", brand: "Lian Li", price: 48000, stock: 6, cut: WHITE,
    desc: "Iconic showcase chassis with reversible layout.", specs: { "Form Factor": "Mid Tower", Glass: "Tempered", Colour: "White" } },
  { photo: 2, cat: "cases", name: "Corsair Carbide Series 600C", brand: "Corsair", price: 36000, stock: 5,
    desc: "Inverted-layout ATX case with sound-dampened panels.", specs: { "Form Factor": "Full Tower", Glass: "Tempered side", Colour: "Black" } },
  { photo: 3, cat: "cases", name: "Dell Vostro Mini Tower Chassis", brand: "Dell", price: 12000, stock: 10,
    desc: "Compact office tower chassis with front I/O and optical bay.", specs: { "Form Factor": "Mini Tower", Bays: "5.25\" optical", Colour: "Black" } },
  { photo: 4, cat: "cases", name: "Corsair Carbide SPEC-OMEGA Red", brand: "Corsair", price: 32000, sale: 29000, stock: 6,
    desc: "Angular gaming case with tempered glass and red accents.", specs: { "Form Factor": "Mid Tower", Glass: "Tempered", Colour: "Black / Red" } },
  { photo: 5, cat: "cases", name: "Cougar Conquer Open-Frame Case", brand: "Cougar", price: 78000, stock: 3,
    desc: "Aluminium open-frame showpiece with three tempered glass panels.", specs: { "Form Factor": "ATX Open Frame", Material: "Aluminium", Colour: "Black / Orange" } },

  // ---------- Gaming desks ----------
  { photo: 6, cat: "gaming-desks", name: "RGB Electric Standing Gaming Desk", brand: "PC Builder", price: 68000, sale: 62000, stock: 5, featured: true, cut: SHADOW,
    desc: "Motorised height adjustment with an RGB-lit carbon desktop.", specs: { Width: "140 cm", Height: "72–118 cm", RGB: "Yes" } },
  { photo: 7, cat: "gaming-desks", name: "L-Shaped Electric Standing Desk", brand: "PC Builder", price: 85000, stock: 4,
    cut: { force: true, tolerance: 40, edgeLimit: 8, crop: [0.13, 0.12, 0.87, 0.88], minComponent: 0.03 },
    desc: "Corner sit-stand desk with a carbon-fibre textured top.", specs: { Size: "160 x 110 cm", Motors: "Dual", Shape: "L-Shape" } },
  { photo: 8, cat: "gaming-desks", name: "IKEA LAGKAPTEN / ALEX Desk (Black)", brand: "IKEA", price: 45000, stock: 6,
    desc: "Wide desk with two ALEX drawer units for storage.", specs: { Width: "200 cm", Drawers: "10", Colour: "Black-brown" } },
  { photo: 9, cat: "gaming-desks", name: "Futuristic White LED Gaming Desk", brand: "PC Builder", price: 72000, stock: 3, cut: WHITE,
    desc: "Sculpted two-tier desk with glowing LED edges and monitor shelf.", specs: { Width: "150 cm", Tiers: "2", Lighting: "LED" } },
  { photo: 10, cat: "gaming-desks", name: "RGB Gaming Desk with Monitor Shelf", brand: "PC Builder", price: 38000, sale: 34000, stock: 8, cut: SHADOW,
    desc: "Z-frame desk with RGB mouse mat and a raised monitor riser.", specs: { Width: "140 cm", Shelf: "Monitor riser", RGB: "Yes" } },
  { photo: 11, cat: "gaming-desks", name: "Wood-Top Standing Desk", brand: "PC Builder", price: 55000, stock: 5, cut: SHADOW,
    desc: "Warm oak-finish top on a steel sit-stand frame.", specs: { Width: "160 cm", Top: "Oak finish", Frame: "Steel" } },

  // ---------- Gaming chairs ----------
  { photo: 12, cat: "gaming-chairs", name: "Red & Black Racing Gaming Chair", brand: "PC Builder", price: 32000, sale: 28500, stock: 12,
    desc: "Bucket-seat racing chair with lumbar and neck pillows.", specs: { Material: "PU Leather", Recline: "155°", "Max Load": "120 kg" } },
  { photo: 13, cat: "gaming-chairs", name: "Secretlab Titan Evo Minecraft Creeper Edition", brand: "Secretlab", price: 155000, stock: 3, featured: true,
    desc: "Officially licensed Creeper edition of the award-winning Titan Evo.", specs: { Material: "SoftWeave Plus Fabric", Recline: "165°", "Max Load": "130 kg" } },
  { photo: 14, cat: "gaming-chairs", name: "Marvel Spider-Man Gaming Chair with Footrest", brand: "Marvel", price: 58000, stock: 5,
    desc: "Spider-Man themed chair with retractable footrest.", specs: { Material: "PU Leather", Footrest: "Retractable", "Max Load": "120 kg" } },
  { photo: 15, cat: "gaming-chairs", name: "Secretlab Titan Evo Attack on Titan Edition", brand: "Secretlab", price: 160000, stock: 2, cut: SHADOW,
    desc: "Survey Corps themed Titan Evo with magnetic memory-foam pillow.", specs: { Material: "NEO Hybrid Leatherette", Recline: "165°", "Max Load": "130 kg" } },
  { photo: 16, cat: "gaming-chairs", name: "Zeanus Purple Gaming Chair with Footrest", brand: "Zeanus", price: 42000, sale: 38000, stock: 7,
    desc: "Massage lumbar pillow and footrest for long gaming sessions.", specs: { Material: "PU Leather", Massage: "Lumbar", Footrest: "Yes" } },
  { photo: 17, cat: "gaming-chairs", name: "White & Black Racing Chair with Footrest", brand: "PC Builder", price: 35000, stock: 9, cut: SHADOW,
    desc: "Clean white racing chair with a pull-out footrest.", specs: { Material: "PU Leather", Recline: "160°", Footrest: "Yes" } },

  // ---------- Monitors ----------
  { photo: 18, cat: "monitors", name: "34\" Curved Ultrawide Gaming Monitor 165Hz", brand: "PC Builder", price: 115000, stock: 5,
    desc: "1500R curved 3440x1440 panel for immersive gaming.", specs: { Size: "34 inch", Resolution: "3440x1440", "Refresh Rate": "165Hz" } },
  { photo: 19, cat: "monitors", name: "Acer Predator X45 Curved OLED", brand: "Acer", price: 420000, sale: 395000, stock: 2, featured: true,
    desc: "45\" 800R OLED with 240Hz and 0.01ms response.", specs: { Size: "45 inch", Resolution: "3440x1440", "Refresh Rate": "240Hz", Panel: "OLED" } },
  { photo: 20, cat: "monitors", name: "27\" QHD IPS Gaming Monitor 170Hz", brand: "PC Builder", price: 68000, stock: 9,
    desc: "Sharp 1440p IPS panel with a height-adjustable stand.", specs: { Size: "27 inch", Resolution: "2560x1440", "Refresh Rate": "170Hz" } },
  { photo: 21, cat: "monitors", name: "AOC CU34G2X 34\" Curved Gaming Monitor", brand: "AOC", price: 98000, sale: 92000, stock: 6, cut: { ...SHADOW, force: true },
    desc: "Curved 144Hz VA ultrawide with red accent stand.", specs: { Size: "34 inch", Resolution: "3440x1440", "Refresh Rate": "144Hz", Panel: "VA" } },
  { photo: 22, cat: "monitors", name: "LG 34UM95 UltraWide Monitor", brand: "LG", price: 88000, stock: 4,
    desc: "21:9 IPS UltraWide with Thunderbolt connectivity.", specs: { Size: "34 inch", Resolution: "3440x1440", Panel: "IPS" } },
  { photo: 23, cat: "monitors", name: "LG 34UC98-W Curved UltraWide", brand: "LG", price: 105000, stock: 4,
    desc: "Curved 21:9 IPS with a sleek silver arc stand.", specs: { Size: "34 inch", Resolution: "3440x1440", Panel: "IPS Curved" } },

  // ---------- Headphones ----------
  { photo: 24, cat: "headphones", name: "Kotion EACH G2000 Gaming Headset (White)", brand: "Kotion EACH", price: 6500, sale: 5500, stock: 25, cut: WHITE,
    desc: "LED-lit over-ear headset with noise-reducing mic.", specs: { Driver: "40mm", Connection: "3.5mm + USB (LED)", Colour: "White" } },
  { photo: 25, cat: "headphones", name: "Logitech Astro A50 Wireless + Base Station", brand: "Astro", price: 95000, stock: 4, featured: true,
    desc: "Premium wireless headset with charging base station.", specs: { Driver: "40mm", Battery: "15+ hours", Connection: "2.4GHz Wireless" } },
  { photo: 26, cat: "headphones", name: "EKSA E900 Pro Gaming Headset", brand: "EKSA", price: 12000, stock: 14,
    desc: "7.1 surround headset with detachable noise-cancelling mic.", specs: { Driver: "50mm", Surround: "Virtual 7.1", Connection: "USB / 3.5mm" } },
  { photo: 27, cat: "headphones", name: "Blue & Purple LED Gaming Headset", brand: "PC Builder", price: 5500, stock: 20,
    desc: "Colourful lightweight headset with flexible mic.", specs: { Driver: "40mm", Connection: "3.5mm", LED: "Yes" } },
  { photo: 28, cat: "headphones", name: "Corsair Virtuoso RGB Wireless SE", brand: "Corsair", price: 58000, sale: 54000, stock: 5,
    desc: "Aluminium wireless headset with broadcast-grade microphone.", specs: { Driver: "50mm", Battery: "20 hours", Connection: "Wireless / USB / 3.5mm" } },
  { photo: 29, cat: "headphones", name: "Corsair HS35 Stereo Gaming Headset", brand: "Corsair", price: 11000, stock: 18,
    desc: "Lightweight stereo headset with memory-foam cushions.", specs: { Driver: "50mm", Connection: "3.5mm", Weight: "254g" } },
  { photo: 30, cat: "headphones", name: "HyperX Cloud II Pink", brand: "HyperX", price: 22000, stock: 8, cut: WHITE,
    desc: "The legendary Cloud II in white and pink.", specs: { Driver: "53mm", Surround: "Virtual 7.1", Connection: "USB / 3.5mm" } },
  { photo: 85, cat: "headphones", name: "ASUS Xonar Essence STX II Sound Card", brand: "ASUS", price: 45000, stock: 3,
    desc: "Audiophile PCIe sound card with a built-in headphone amplifier.", specs: { Interface: "PCIe", SNR: "124 dB", "Headphone Amp": "Yes" } },

  // ---------- Mice ----------
  { photo: 31, cat: "mice", name: "Purple LED Wired Gaming Mouse", brand: "PC Builder", price: 3500, stock: 30,
    desc: "Six-button mouse with breathing purple LEDs.", specs: { DPI: "3200", Buttons: "6", Connection: "Wired" } },
  { photo: 32, cat: "mice", name: "Blue LED Mechanical Gaming Mouse", brand: "PC Builder", price: 4000, sale: 3500, stock: 25,
    desc: "Aggressive styling with blue backlight and side vents.", specs: { DPI: "3200", Buttons: "7", Connection: "Wired" } },
  { photo: 33, cat: "mice", name: "MEETION M915 Gaming Mouse (White)", brand: "MEETION", price: 3800, stock: 20,
    desc: "Ergonomic LED mouse with adjustable DPI.", specs: { DPI: "4800", Buttons: "7", Connection: "Wired" } },
  { photo: 34, cat: "mice", name: "MEETION M915 Gaming Mouse (Black)", brand: "MEETION", price: 3800, stock: 22,
    desc: "Black edition with red LED lighting.", specs: { DPI: "4800", Buttons: "7", Connection: "Wired" } },
  { photo: 35, cat: "mice", name: "Chrome Arc Ergonomic Mouse", brand: "PC Builder", price: 5500, stock: 12,
    desc: "Sleek arched design with glossy chrome finish.", specs: { DPI: "2400", Buttons: "4", Connection: "Wired" } },
  { photo: 36, cat: "mice", name: "ROCCAT Kone AIMO (White)", brand: "ROCCAT", price: 18000, sale: 16000, stock: 7, featured: true, cut: WHITE,
    desc: "Ergonomic RGBA mouse with Owl-Eye sensor.", specs: { DPI: "16,000", Buttons: "23 functions", Connection: "Wired" } },

  // ---------- RGB lights ----------
  { photo: 37, cat: "rgb-lights", name: "RGB LED Strip Light 5m", brand: "PC Builder", price: 3500, stock: 40,
    desc: "Colour-changing LED strip reel for desks and rooms.", specs: { Length: "5m", Control: "Remote", Colours: "16 million" } },
  { photo: 38, cat: "rgb-lights", name: "Addressable RGB LED Strip Kit with Remote", brand: "PC Builder", price: 5500, sale: 4800, stock: 30,
    desc: "Complete kit with adapter and IR remote.", specs: { Length: "5m", Control: "IR Remote", Power: "Adapter" } },
  { photo: 39, cat: "rgb-lights", name: "USB RGB LED Strip with 24-Key Remote", brand: "PC Builder", price: 2500, stock: 45,
    desc: "USB-powered strip — perfect for monitor backlighting.", specs: { Length: "3m", Power: "USB", Control: "24-key remote" } },
  { photo: 40, cat: "rgb-lights", name: "COLORRGB Neon Rope Lights", brand: "COLORRGB", price: 9500, stock: 15, featured: true,
    desc: "Flexible neon rope with app control and music sync.", specs: { Length: "5m", Control: "App + Remote", "Music Sync": "Yes" } },
  { photo: 41, cat: "rgb-lights", name: "100ft Neon Rope Lights (2 Rolls)", brand: "PC Builder", price: 18000, sale: 16000, stock: 10,
    desc: "Indoor/outdoor neon rope lights for big setups.", specs: { Length: "2 x 50ft", Control: "App + Remote", Rating: "IP65" } },
  { photo: 42, cat: "rgb-lights", name: "USB Warm White LED Strip with Dimmer", brand: "PC Builder", price: 2200, stock: 35,
    desc: "Soft warm-white desk lighting with inline dimmer.", specs: { Length: "3m", Colour: "Warm White", Control: "Dimmer" } },

  // ---------- Keyboards (new) ----------
  { photo: 43, cat: "keyboards", name: "GravaStar Mercury K1 Lite", brand: "GravaStar", price: 24000, stock: 8, cut: { crop: [0, 0, 1, 0.7] },
    desc: "75% gasket-mount mechanical keyboard with gradient keycaps.", specs: { Layout: "75%", Switches: "Hot-swappable", Connection: "Wired / Wireless" } },
  { photo: 44, cat: "keyboards", name: "60% RGB Mechanical Keyboard (Grey)", brand: "PC Builder", price: 9500, sale: 8500, stock: 15,
    desc: "Compact 61-key board with RGB backlight and detachable cable.", specs: { Layout: "60%", Switches: "Red", Connection: "USB-C" } },
  { photo: 45, cat: "keyboards", name: "GravaStar Mercury K1 Pro", brand: "GravaStar", price: 38000, stock: 5, featured: true, cut: { crop: [0, 0, 1, 0.72] },
    desc: "Mecha-styled aluminium keyboard with graffiti keycaps.", specs: { Layout: "75%", Frame: "Aluminium alloy", Connection: "Tri-mode" } },
  { photo: 46, cat: "keyboards", name: "Wireless 65% RGB Keyboard (White)", brand: "PC Builder", price: 14000, stock: 10, cut: WHITE,
    desc: "White 65% board with a glowing RGB side bar and 2.4GHz dongle.", specs: { Layout: "65%", Connection: "2.4GHz / Bluetooth", RGB: "Side light bar" } },
  { photo: 47, cat: "keyboards", name: "RGB Membrane Gaming Keyboard", brand: "PC Builder", price: 4500, stock: 30,
    desc: "Quiet full-size keyboard with rainbow backlight.", specs: { Layout: "Full size", Switches: "Membrane", Connection: "USB" } },
  { photo: 48, cat: "keyboards", name: "AULA Gaming Keyboard with Phone Holder", brand: "AULA", price: 7500, sale: 6500, stock: 18,
    desc: "Metal-plate keyboard with RGB edges and a phone stand.", specs: { Layout: "Full size", Frame: "Metal", Extras: "Phone holder" } },

  // ---------- Mouse pads (new) ----------
  { photo: 49, cat: "mouse-pads", name: "XXL Black Extended Mouse Pad", brand: "PC Builder", price: 2500, stock: 50,
    desc: "Desk-sized pad with stitched edges.", specs: { Size: "900 x 400 mm", Thickness: "3mm", Base: "Non-slip rubber" } },
  { photo: 50, cat: "mouse-pads", name: "Misty Forest XXL Desk Mat", brand: "PC Builder", price: 3200, stock: 30, cut: { ...SHADOW, force: true },
    desc: "Calm forest artwork on a smooth speed surface.", specs: { Size: "800 x 300 mm", Thickness: "3mm", Edges: "Stitched" } },
  { photo: 51, cat: "mouse-pads", name: "TECKNET RGB Gaming Mouse Pad", brand: "TECKNET", price: 4500, sale: 3900, stock: 20, featured: true,
    desc: "RGB-lit edges with 14 lighting modes.", specs: { Size: "800 x 300 mm", RGB: "14 modes", Connection: "USB" } },
  { photo: 52, cat: "mouse-pads", name: "ROCKPAPA Geometric XXL Mouse Pad", brand: "ROCKPAPA", price: 3000, stock: 25, cut: { ...SHADOW, force: true },
    desc: "Neon geometric design on an extended pad.", specs: { Size: "800 x 300 mm", Thickness: "3mm", Base: "Rubber" } },
  { photo: 53, cat: "mouse-pads", name: "ASUS ROG Sheath", brand: "ASUS", price: 7500, stock: 12,
    desc: "Extra-large ROG pad with anti-fray stitching.", specs: { Size: "900 x 440 mm", Thickness: "3mm", Surface: "Micro-weave" } },
  { photo: 54, cat: "mouse-pads", name: "ASUS ROG Sheath BLK LTD", brand: "ASUS", price: 8500, stock: 8,
    desc: "Limited black edition with ROG typography.", specs: { Size: "900 x 440 mm", Thickness: "3mm", Edition: "Limited" } },
  { photo: 55, cat: "mouse-pads", name: "ASUS ROG Logo Gaming Mouse Pad", brand: "ASUS", price: 5500, stock: 14,
    desc: "Minimal black pad with the ROG eye logo.", specs: { Size: "450 x 400 mm", Thickness: "3mm", Surface: "Cloth" } },

  // ---------- Case fans (new) ----------
  { photo: 56, cat: "case-fans", name: "Triple 120mm Fan Frame Kit (Black)", brand: "PC Builder", price: 9500, stock: 12,
    desc: "Three high-pressure fans pre-mounted in a single frame.", specs: { Size: "3 x 120mm", Speed: "Up to 2000 RPM", Lighting: "None" } },
  { photo: 57, cat: "case-fans", name: "ARGB Square-Frame 120mm Fans (3-Pack)", brand: "PC Builder", price: 11000, sale: 9800, stock: 10,
    desc: "Infinity-mirror hub and edge lighting.", specs: { Size: "120mm", Pack: "3", Lighting: "ARGB" } },
  { photo: 58, cat: "case-fans", name: "ARGB Rainbow 120mm Case Fans (3-Pack)", brand: "PC Builder", price: 7500, stock: 20, featured: true,
    desc: "Vivid rainbow fans with hub controller.", specs: { Size: "120mm", Pack: "3", Lighting: "ARGB" } },
  { photo: 59, cat: "case-fans", name: "Ant Esports Dual Ring ARGB 120mm Fan", brand: "Ant Esports", price: 2200, stock: 40,
    desc: "Dual-ring ARGB fan for bright builds.", specs: { Size: "120mm", Speed: "1200 RPM", Lighting: "Dual ring ARGB" } },
  { photo: 60, cat: "case-fans", name: "Corsair ML120 Magnetic Levitation Fan", brand: "Corsair", price: 5500, stock: 15,
    desc: "Premium maglev bearing fan for quiet high airflow.", specs: { Size: "120mm", Speed: "400–2400 RPM", Bearing: "Magnetic levitation" } },
  { photo: 61, cat: "case-fans", name: "Standard 120mm Black Case Fan", brand: "PC Builder", price: 900, stock: 60,
    desc: "Reliable budget fan for extra airflow.", specs: { Size: "120mm", Speed: "1200 RPM", Connector: "3-pin / Molex" } },

  // ---------- Motherboards ----------
  { photo: 62, cat: "motherboards", name: "Gigabyte H610M S2H DDR4", brand: "Gigabyte", price: 26000, sale: 24000, stock: 14,
    desc: "Budget micro-ATX board for 12th–14th gen Intel.", specs: { Socket: "LGA1700", "Form Factor": "Micro-ATX", Memory: "DDR4" } },
  { photo: 63, cat: "motherboards", name: "ASUS ROG Maximus XII Extreme", brand: "ASUS", price: 145000, stock: 2, cut: { minComponent: 0.08 },
    desc: "Flagship Z490 board with LiveDash OLED.", specs: { Socket: "LGA1200", "Form Factor": "E-ATX", Chipset: "Z490" } },
  { photo: 64, cat: "motherboards", name: "NZXT N7 Z790 White", brand: "NZXT", price: 82000, stock: 5, featured: true, cut: WHITE,
    desc: "Clean all-white board with full-cover armour.", specs: { Socket: "LGA1700", "Form Factor": "ATX", Chipset: "Z790" } },
  { photo: 65, cat: "motherboards", name: "Gigabyte GA-Z170X-Gaming G1", brand: "Gigabyte", price: 55000, stock: 3,
    desc: "Enthusiast Z170 board with Creative Sound Core3D audio.", specs: { Socket: "LGA1151", "Form Factor": "E-ATX", Chipset: "Z170" } },
  { photo: 66, cat: "motherboards", name: "ASRock X99 OC Formula", brand: "ASRock", price: 62000, stock: 2,
    desc: "Overclocking-focused X99 board in signature yellow.", specs: { Socket: "LGA2011-3", "Form Factor": "ATX", Chipset: "X99" } },
  { photo: 67, cat: "motherboards", name: "ASRock Fatal1ty X99X Killer/3.1", brand: "ASRock", price: 58000, sale: 52000, stock: 3,
    desc: "Gaming X99 board with Killer LAN and USB 3.1.", specs: { Socket: "LGA2011-3", "Form Factor": "ATX", Chipset: "X99" } },

  // ---------- Processors ----------
  { photo: 68, cat: "processors", name: "Intel Core 2 Duo E8400", brand: "Intel", price: 3500, stock: 10,
    desc: "Classic dual-core for legacy builds.", specs: { Cores: "2", Clock: "3.0 GHz", Socket: "LGA775" } },
  { photo: 69, cat: "processors", name: "Intel Xeon E5-2690 v4", brand: "Intel", price: 28000, stock: 6,
    desc: "14-core server CPU for workstations.", specs: { Cores: "14", Threads: "28", Socket: "LGA2011-3" } },
  { photo: 70, cat: "processors", name: "Intel Core i5-10400F", brand: "Intel", price: 32000, sale: 29500, stock: 18,
    desc: "6-core value gaming processor.", specs: { Cores: "6", Threads: "12", "Boost Clock": "4.3 GHz", Socket: "LGA1200" } },
  { photo: 71, cat: "processors", name: "Intel Core i9-10980XE Extreme Edition", brand: "Intel", price: 185000, stock: 2,
    cut: { force: true, tolerance: 75, edgeLimit: 8, crop: [0.1, 0, 0.8, 0.88] },
    desc: "18-core X-series HEDT processor.", specs: { Cores: "18", Threads: "36", "Boost Clock": "4.8 GHz", Socket: "LGA2066" } },
  { photo: 72, cat: "processors", name: "Intel Core i7-10700K", brand: "Intel", price: 72000, stock: 7, cut: { force: true },
    desc: "8-core unlocked chip for gaming and streaming.", specs: { Cores: "8", Threads: "16", "Boost Clock": "5.1 GHz", Socket: "LGA1200" } },
  { photo: 73, cat: "processors", name: "AMD Ryzen 7 7800X3D", brand: "AMD", price: 125000, sale: 115000, stock: 10, featured: true,
    cut: { force: true, tolerance: 25, crop: [0, 0, 0.855, 1], erase: [0.75, 0.84, 0.25, 0.16] },
    desc: "The best gaming CPU with 3D V-Cache.", specs: { Cores: "8", Threads: "16", "Boost Clock": "5.0 GHz", Socket: "AM5" } },

  // ---------- Power supplies ----------
  { photo: 74, cat: "power-supplies", name: "Corsair VS650", brand: "Corsair", price: 17000, stock: 20,
    desc: "Reliable 650W 80+ White PSU.", specs: { Wattage: "650W", Efficiency: "80+ White", Modular: "No" } },
  { photo: 75, cat: "power-supplies", name: "BlitzWolf BW-GP1 750W", brand: "BlitzWolf", price: 24000, sale: 21500, stock: 9,
    desc: "750W Gold semi-modular PSU with red fan grille.", specs: { Wattage: "750W", Efficiency: "80+ Gold", Modular: "Semi" } },
  { photo: 76, cat: "power-supplies", name: "RGB Fan 600W Power Supply", brand: "PC Builder", price: 9500, stock: 18,
    desc: "Budget PSU with a rainbow RGB fan.", specs: { Wattage: "600W", Fan: "120mm RGB", Modular: "No" } },
  { photo: 77, cat: "power-supplies", name: "Red Fan 500W Power Supply", brand: "PC Builder", price: 7500, stock: 22,
    desc: "Entry-level 500W PSU with sleeved cables.", specs: { Wattage: "500W", Fan: "120mm", Modular: "No" } },
  { photo: 78, cat: "power-supplies", name: "Chieftec Core 700W", brand: "Chieftec", price: 19000, stock: 11,
    desc: "80+ Gold efficiency in a compact housing.", specs: { Wattage: "700W", Efficiency: "80+ Gold", Modular: "No" } },
  { photo: 79, cat: "power-supplies", name: "Xplus Power 725W", brand: "Xplus", price: 12000, stock: 15,
    desc: "725W PSU with large silent fan.", specs: { Wattage: "725W", Fan: "140mm", Modular: "No" } },

  // ---------- Graphics cards ----------
  { photo: 80, cat: "graphics-cards", name: "NVIDIA GeForce RTX 4080 Founders Edition", brand: "NVIDIA", price: 330000, sale: 315000, stock: 3, featured: true,
    desc: "Flow-through cooler and 16GB GDDR6X for 4K gaming.", specs: { VRAM: "16GB GDDR6X", "Boost Clock": "2.51 GHz", TDP: "320W" } },
  { photo: 81, cat: "graphics-cards", name: "Sapphire NITRO+ Radeon RX 7900 XTX Vapor-X", brand: "Sapphire", price: 310000, stock: 3,
    desc: "AMD flagship with 24GB VRAM and ARGB light bar.", specs: { VRAM: "24GB GDDR6", "Boost Clock": "2.68 GHz", TDP: "420W" } },
  { photo: 82, cat: "graphics-cards", name: "Sapphire NITRO+ Radeon RX 6800 XT", brand: "Sapphire", price: 165000, sale: 155000, stock: 4,
    desc: "Triple-fan RDNA 2 card for 1440p high-refresh gaming.", specs: { VRAM: "16GB GDDR6", "Boost Clock": "2.36 GHz", TDP: "300W" } },
  { photo: 83, cat: "graphics-cards", name: "EVGA GeForce RTX 2080 Super XC Hybrid", brand: "EVGA", price: 120000, stock: 2,
    desc: "Hybrid liquid-cooled RTX 2080 Super.", specs: { VRAM: "8GB GDDR6", Cooling: "Hybrid AIO", TDP: "250W" } },
  { photo: 84, cat: "graphics-cards", name: "Palit GeForce GTX 1050 Ti StormX", brand: "Palit", price: 32000, stock: 12,
    desc: "Compact single-fan card for esports titles.", specs: { VRAM: "4GB GDDR5", "Boost Clock": "1.39 GHz", TDP: "75W" } },
  { photo: 86, cat: "graphics-cards", name: "ASUS ROG Poseidon GTX 780 Platinum", brand: "ASUS", price: 45000, stock: 2,
    desc: "Collector's ROG card with hybrid air/water cooler.", specs: { VRAM: "3GB GDDR5", Cooling: "DirectCU H2O", TDP: "250W" } },

  // ---------- Cooling ----------
  { photo: 87, cat: "cooling", name: "Intel Stock CPU Cooler", brand: "Intel", price: 1500, stock: 40,
    desc: "Low-profile aluminium cooler for everyday CPUs.", specs: { Type: "Air", Fan: "90mm", Socket: "LGA1200 / 1700" } },
  { photo: 88, cat: "cooling", name: "DeepCool AK620 White", brand: "DeepCool", price: 18000, sale: 16500, stock: 10, featured: true, cut: WHITE,
    desc: "Dual-tower air cooler in clean white.", specs: { Type: "Air", Fans: "2 x 120mm", "Heat Pipes": "6" } },
  { photo: 89, cat: "cooling", name: "Gigabyte AORUS ATC800", brand: "Gigabyte", price: 22000, stock: 6,
    desc: "RGB tower cooler with an eagle-logo top cover.", specs: { Type: "Air", Fans: "2 x 120mm", RGB: "Yes" } },
  { photo: 90, cat: "cooling", name: "Antec Vortex 360 ARGB AIO", brand: "Antec", price: 32000, stock: 7,
    desc: "360mm liquid cooler with ARGB fans and pump.", specs: { Type: "AIO", Radiator: "360mm", RGB: "ARGB" } },
  { photo: 91, cat: "cooling", name: "GMRGB Dual-Fan RGB CPU Cooler", brand: "GMRGB", price: 5500, stock: 20,
    desc: "Budget twin-fan tower with rainbow lighting.", specs: { Type: "Air", Fans: "2 x 90mm", "Heat Pipes": "2" } },
  { photo: 92, cat: "cooling", name: "Thermalright Macho Rev.B", brand: "Thermalright", price: 14000, stock: 8,
    desc: "Big quiet heatsink with a 140mm TY-147 fan.", specs: { Type: "Air", Fan: "140mm", "Heat Pipes": "6" } },

  // ---------- Memory ----------
  { photo: 93, cat: "memory", name: "T-Force Delta RGB DDR4 32GB (White)", brand: "TeamGroup", price: 26000, sale: 23500, stock: 14, cut: { ...WHITE, force: true },
    desc: "Wide-angle RGB lighting in a white heat spreader.", specs: { Capacity: "32GB (2x16)", Speed: "3600 MHz", Latency: "CL18" } },
  { photo: 94, cat: "memory", name: "G.Skill Trident Z5 RGB DDR5 32GB", brand: "G.Skill", price: 36000, stock: 12, featured: true,
    desc: "High-speed DDR5 with sleek RGB light bar.", specs: { Capacity: "32GB (2x16)", Speed: "6400 MHz", Latency: "CL32" } },
  { photo: 95, cat: "memory", name: "G.Skill Trident Z RGB DC 64GB", brand: "G.Skill", price: 58000, stock: 4,
    desc: "Double-capacity DIMMs for heavy workloads.", specs: { Capacity: "64GB (2x32)", Speed: "3200 MHz", Latency: "CL14" } },
  { photo: 96, cat: "memory", name: "HyperX Fury RGB DDR4 16GB", brand: "HyperX", price: 14000, stock: 20,
    desc: "Plug-and-play overclocking with RGB.", specs: { Capacity: "16GB (2x8)", Speed: "3200 MHz", Latency: "CL16" } },
  { photo: 97, cat: "memory", name: "T-Force Vulcan Z DDR4 16GB", brand: "TeamGroup", price: 11500, sale: 10500, stock: 25,
    desc: "Low-profile grey heat spreader, great value.", specs: { Capacity: "16GB (2x8)", Speed: "3200 MHz", Latency: "CL16" } },
  { photo: 98, cat: "memory", name: "Patriot Viper 4 DDR4 16GB", brand: "Patriot", price: 12500, stock: 16,
    desc: "Aggressive red heat shield for gamers.", specs: { Capacity: "16GB (2x8)", Speed: "3600 MHz", Latency: "CL17" } },

  // ---------- Storage ----------
  { photo: 99, cat: "storage", name: "Samsung 990 PRO 2TB NVMe SSD", brand: "Samsung", price: 52000, sale: 48000, stock: 12, featured: true,
    desc: "Top-tier PCIe 4.0 performance.", specs: { Capacity: "2TB", Read: "7450 MB/s", Interface: "PCIe 4.0 x4" } },
  { photo: 100, cat: "storage", name: "Samsung 980 PRO 2TB NVMe SSD", brand: "Samsung", price: 45000, stock: 10,
    desc: "Fast Gen4 SSD for gaming and creation.", specs: { Capacity: "2TB", Read: "7000 MB/s", Interface: "PCIe 4.0 x4" } },
  { photo: 101, cat: "storage", name: "Samsung 970 EVO Plus 2TB NVMe SSD", brand: "Samsung", price: 38000, stock: 14,
    desc: "Proven Gen3 SSD with excellent endurance.", specs: { Capacity: "2TB", Read: "3500 MB/s", Interface: "PCIe 3.0 x4" } },
  { photo: 102, cat: "storage", name: "Nextorage G Series 2TB NVMe SSD", brand: "Nextorage", price: 34000, sale: 31000, stock: 8, cut: SHADOW,
    desc: "PS5-ready Gen4 SSD with high sustained speeds.", specs: { Capacity: "2TB", Read: "7300 MB/s", Interface: "PCIe 4.0 x4" } },
  { photo: 103, cat: "storage", name: "Kingston A2000 1TB NVMe SSD", brand: "Kingston", price: 18000, stock: 20,
    desc: "Affordable NVMe upgrade for any PC.", specs: { Capacity: "1TB", Read: "2200 MB/s", Interface: "PCIe 3.0 x4" } },
  { photo: 104, cat: "storage", name: "Samsung PM983 Enterprise NVMe SSD", brand: "Samsung", price: 42000, stock: 5, cut: SHADOW,
    desc: "Data-centre grade M.2 22110 drive with power-loss protection.", specs: { Capacity: "1.92TB", Read: "3000 MB/s", "Form Factor": "M.2 22110" } },
];
