// Turns the photos in E:\photos into transparent product images under public/products and
// writes scripts/import-photos.sql to replace the photo-backed products in Supabase.
// Usage: node scripts/import-photos.cjs [photosDir]
const fs = require("fs");
const path = require("path");
const sharp = require("sharp");
const { cutout } = require("./cutout.cjs");
const catalog = require("./catalog.cjs");

const PHOTOS = process.argv[2] ?? "E:/photos";
const OUT_DIR = path.join(__dirname, "..", "public", "products");

const slugify = (value) =>
  value.toLowerCase().replace(/"/g, "in").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
const sql = (value) => (value == null ? "null" : `'${String(value).replace(/'/g, "''")}'`);

(async () => {
  const files = fs
    .readdirSync(PHOTOS)
    .filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
    .map((f) => ({ f, t: fs.statSync(path.join(PHOTOS, f)).mtimeMs }))
    .sort((a, b) => a.t - b.t)
    .map((x) => x.f);
  if (files.length !== catalog.length) {
    throw new Error(`Expected ${catalog.length} photos, found ${files.length}`);
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  const rows = [];
  const slugs = new Set();

  for (const item of catalog) {
    const slug = slugify(item.name);
    if (slugs.has(slug)) throw new Error(`Duplicate slug ${slug}`);
    slugs.add(slug);

    const { image, removable } = await cutout(path.join(PHOTOS, files[item.photo]), item.cut ?? {});
    let out = sharp(await image.resize(800, 800, { fit: "inside", withoutEnlargement: true }).png().toBuffer());
    if (!removable) {
      // Photos that keep their own (dark scene) background get rounded corners to sit nicely in cards.
      const { width, height } = await out.metadata();
      const radius = Math.round(Math.min(width, height) * 0.06);
      const mask = Buffer.from(`<svg width="${width}" height="${height}"><rect width="${width}" height="${height}" rx="${radius}" ry="${radius}"/></svg>`);
      out = sharp(await out.ensureAlpha().composite([{ input: mask, blend: "dest-in" }]).png().toBuffer());
    }
    await out.webp({ quality: 84, alphaQuality: 90 }).toFile(path.join(OUT_DIR, `${slug}.webp`));

    rows.push(
      `(${sql(item.name)}, ${sql(slug)}, ${sql(item.desc)}, ${sql(item.brand)}, ${sql(item.cat)}, ${item.price}, ` +
        `${item.sale ?? "null"}, ${item.stock}, ${sql(JSON.stringify(item.specs))}, ${sql(`/products/${slug}.webp`)}, ${Boolean(item.featured)})`,
    );
    process.stdout.write(".");
  }

  const categories = [...new Set(catalog.map((i) => i.cat))];
  const statement = `-- Generated by scripts/import-photos.cjs
begin;
delete from public.products p using public.categories c
  where p.category_id = c.id and c.slug in (${categories.map(sql).join(", ")});
insert into public.products (name, slug, description, brand, category_id, price, sale_price, stock, specs, image_url, featured)
select v.name, v.slug, v.description, v.brand, c.id, v.price, v.sale_price, v.stock, v.specs::jsonb, v.image_url, v.featured
from (values
${rows.join(",\n")}
) as v(name, slug, description, brand, cat_slug, price, sale_price, stock, specs, image_url, featured)
join public.categories c on c.slug = v.cat_slug;
commit;
`;
  fs.writeFileSync(path.join(__dirname, "import-photos.sql"), statement);
  console.log(`\n${rows.length} products, ${categories.length} categories -> scripts/import-photos.sql`);
})();
